f = open('bot.py', 'r')
c = f.read()
f.close()
c = c.replace(chr(8216), chr(39))
c = c.replace(chr(8217), chr(39))
c = c.replace(chr(8220), chr(34))
c = c.replace(chr(8221), chr(34))
f = open('bot.py', 'w')
f.write(c)
f.close()
print('Fixed')
